### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by otisg** [sematext/logsene-cli#5]
When trying `logsene search` it prompts me to login. I do so, but get

No active sessions. Please log in using your Sematext account:
Enter your username: xxxxxxx
Enter your password:
Login was not successful{}
Unable to login: Login was not successful. Possibly wrong username or password.

**Comment by otisg** [comment]
I wonder if having a -v(erbose) mode that just logs what endpoints its calling would be handy for things like this, @mbonaci

**Comment by fernviridian** [comment]
Any updates on this? My team would love to use this tool for our Sematext logs.

**Comment by mbonaci** [comment]
Hi @tgjamin, let me check and I'll get back to you.
Thx for reporting.

**Comment by megastef** [comment]
@otisg logsene-cli has --trace option for verbose output

**Comment by fernviridian** [comment]
I decided to do some manual testing with curl to see what I could find.

Using the endpoint the main web ui uses: 

```
$ curl 'https://apps.sematext.com/users-web/ua/api/login' -H 'Pragma: no-cache' -H 'Origin: https://apps.sematet.com' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.8' -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept: application/json, text/plain, */*' -H 'Cache-Control: no-cache' -H 'Referer: https://apps.sematext.com/ui/login' -H 'Connection: keep-alive' --data-binary '{"loginName":"<redacted>","password":"<redacted>}' --compressed 
{
  "success" : true,
  "message" : "Logged-in successfully",
  "data" : {
    "userInfo" : {
      "loggedInUser" : "<redacted>",
      "userRole" : "OWNER"
    }
  }
```

https://github.com/sematext/logsene-cli/blob/master/lib/config.js#L20
https://github.com/sematext/logsene-cli/blob/master/lib/logsene-api.js#L56

Using the endpoint specified in the logsene-cli:

```
  curl 'https://apps.sematext.com/users-web/api/v2/account/login' -H 'Pragma: no-cache' -H 'Origin: https://apps.sematext.com' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.8' -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept: application/json, text/plain, */*' -H 'Cache-Control: no-cache' -H 'Referer: https://apps.sematext.com/ui/login' -H 'Connection: keep-alive' --data-binary '{"loginName":"<redacted>","password":"<redacted>"}' --compressed -vvv
  
  * upload completely sent off: 75 out of 75 bytes
  < HTTP/1.1 401 Unauthorized
  < Cache-Control: no-cache
  < Content-Type: application/json
  < Date: Fri, 07 Jul 2017 17:12:24 GMT
  < Expires: 0
  < Pragma: no-cache
  < Server: Jetty(9.2.11.v20150529)
  < Set-Cookie: AWSELB=0FF5C7C91A5831F0B9801439C725313F340012932CF586D729D3B402CEEC54EA2C17E88EEB734F03CE4FA492AFD2BD60487CB5503DAA9BCBDC5BC6E787F6C6DAF5D993F663;PATH=/;MAX-AGE=3600
  < Via: 1.1 apps.sematext.com
  < X-Content-Type-Options: nosniff
  < X-Frame-Options: DENY
  < X-XSS-Protection: 1; mode=block
  < Content-Length: 119
  < Connection: keep-alive
  <
  {
    "success" : false,
    "message" : "Not authenticated - provide valid authentication info for api/v2/account/login"
  * Curl_http_done: called premature == 0
  * Connection #0 to host apps.sematext.com left intact
```

The cli also specifies that the that the username key is `username` while the web ui uses `loginName` https://github.com/sematext/logsene-cli/blob/master/lib/logsene-api.js#L58

I tried both for the logsene-cli endpoint, but neither worked. 

Maybe the api endpoint is wrong for the CLI or the POST parameters are off?

**Comment by otisg** [comment]
That is what I suspect might be the case, @tgjamin .  Let's see what @mbonaci says on Monday.

**Comment by mbonaci** [comment]
Hi @tgjamin,
sorry for your troubles, once again.
There are multiple issues.
First issue is related to `login`.
We recently deployed new API and failed to allow (in our backend security rules) a separate `login` endpoint that logsene-cli uses.
That issue is now fixed.

The second issue is related to Elasticsearch. 
We recently upgraded our ES stack to the latest version and it just so happens that Elastic changed ES query API (removal of `filters`).
This is currently being refactored.
You can expect further info tomorrow, at the latest.

**Comment by mbonaci** [comment]
Hi @tgjamin,
I've just published version `2.0.1` to `npm`.
Everything should work now.

After installing new version I recommend that you spend some time in `logsene --help` in order to leverage all the capabilities of this library :)

Of course, if anything goes wrong we are here to help.
Thanks for using our product and library and have fun searching.

**Comment by fernviridian** [comment]
I updated my logsene-cli to `2.0.1` and removed my `~/.config/configstore/logsene/ben.json` file. I then logged in with `logsene search` which was able to retrieve my api key and write that to the `ben.json` file, but still fails:
```
logsene search
No active sessions. Please log in using your Sematext account:
Enter your username: ben@<domain>
Enter your password:
Successfuly logged in and retrieved API key.
Successfuly established Logsene Docker-Logging application session.
ES stream had an error or closed early.
```

With the cli, I also had to manually edit my `ben.json` file to include my `"appKey": "<redacted>"` as the cli did not set this token via `logsene config set --token <redacted>`.

When manually turning on tracing (setting via CLI does not work) by adding `	"trace": true` to the config.json file, and running `logsene search`, I get the following error:
```
$ logsene search "foo"
sessionStart: 2017-07-17T17:12:29.882Z
Got API key from local config: <redacted>
Got APP key from local config: <redacted>
Initializing ES with log level trace
Elasticsearch INFO: 2017-07-17T17:13:48Z
  Adding connection to http://logsene-receiver.sematext.com/

Search called with arguments: {"_":["search","foo"]}

adjustQuery: adjusted query to foo
isSOBT(argv.op): false
Returning query from getQuerySync:
{"query_string":{"query":"foo","default_operator":"OR"}}

getTimeFilterSync returning:
{"range":{"@timestamp":{"gte":"2017-07-17T16:13:48.709Z"}}}

Search: sending to logsene-api:
{"appKey":"<redacted>","offset":0,"logLevel":"trace","body":{"query":{"filtered":{"query":{"query_string":{"query":"foo","default_operator":"OR"}},"filter":{"range":{"@timestamp":{"gte":"2017-07-17T16:13:48.709Z"}}}}},"sort":[{"@timestamp":{"order":"asc"}}]},"size":200}

Elasticsearch DEBUG: 2017-07-17T17:13:48Z
  starting request {
    "method": "POST",
    "path": "/<redacted>/_search",
    "body": {
      "query": {
        "filtered": {
          "query": {
            "query_string": {
              "query": "foo",
              "default_operator": "OR"
            }
          },
          "filter": {
            "range": {
              "@timestamp": {
                "gte": "2017-07-17T16:13:48.709Z"
              }
            }
          }
        }
      },
      "sort": [
        {
          "@timestamp": {
            "order": "asc"
          }
        }
      ]
    },
    "query": {
      "from": 0,
      "size": 50
    }
  }


Elasticsearch TRACE: 2017-07-17T17:13:48Z
  -> POST http://logsene-receiver.sematext.com:80/<redacted>/_search?from=0&size=50
  {
    "query": {
      "filtered": {
        "query": {
          "query_string": {
            "query": "foo",
            "default_operator": "OR"
          }
        },
        "filter": {
          "range": {
            "@timestamp": {
              "gte": "2017-07-17T16:13:48.709Z"
            }
          }
        }
      }
    },
    "sort": [
      {
        "@timestamp": {
          "order": "asc"
        }
      }
    ]
  }
  <- 400
  {
    "error": {
      "root_cause": [
        {
          "type": "parsing_exception",
          "reason": "no [query] registered for [filtered]",
          "line": 1,
          "col": 139
        }
      ],
      "type": "parsing_exception",
      "reason": "no [query] registered for [filtered]",
      "line": 1,
      "col": 139
    },
    "status": 400
  }
```

Two things:
1. When I manually run: `curl -X POST https://logsene-receiver.sematext.com/<my read only token>/_search?from=0&size=50` I get back the expected logs without error. This also works with the Plain HTTP request: `curl -X POST http://logsene-receiver.sematext.com:80/<my read only token>/_search?from=0&size=50`. 

2. The CLI is using Plain HTTP and not using HTTP+TLS, and therefore is leaking my token over the internet unencrypted.

**Comment by mbonaci** [comment]
@tgjamin this seems to be the old query syntax (includes `filtered`).
Have you possibly `npm link`-ed some locally cloned repo so it ends up being used instead of the global one?

**Comment by fernviridian** [comment]
@mbonaci I installed the cli in a fresh node docker container. This has resolved issues setting configuration file settings. Search now works as it should, but requests are still over unencrypted HTTP when searching.

**Comment by mbonaci** [comment]
OK, thanks, I'll look into the security issue.

**Comment by mbonaci** [comment]
Hi @tgjamin,
I've just pushed (and released to NPM) v2.1.0 which talks to both, our API server and our ES via HTTPS.
Thanks for this feedback. Very valuable.
The offer to ping us back if needed still stands, of course.
